# Generated by Django 5.1.7 on 2025-04-01 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('lyrics', models.TextField()),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyric', to='music.track')),
            ],
        ),
    ]
