# Generated by Django 5.1.7 on 2025-04-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_lyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='music.track'),
        ),
        migrations.AlterUniqueTogether(
            name='lyric',
            unique_together={('track', 'artist_name')},
        ),
    ]
