# Generated by Django 5.1.7 on 2025-04-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_lyric_track_alter_lyric_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCloudWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('stream_url', models.TextField()),
                ('artwork_url', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('recommended_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='music.soundcloudwidget')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='music.soundcloudwidget')),
            ],
        ),
    ]
