# Generated by Django 5.1.7 on 2025-04-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_soundcloudwidget_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('discogs_url', models.URLField()),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discogs_release', to='music.track')),
            ],
        ),
    ]
